In [1]:
import pandas as pd
from copy import deepcopy
import warnings
def ignore_warn(*args,**kwargs):
    pass
warnings.warn = ignore_warn

In [2]:
tele = pd.read_csv('tele.csv')
trans = pd.read_csv('trans.csv')
medical = pd.read_csv('medical.csv')
car = pd.read_csv('car.csv')
total_df_list = [tele,trans,medical,car]

In [3]:
for i,df in enumerate(total_df_list):
    df['model'] = i
    del df['Unnamed: 0']
    del df['code']
    for column_name in df.columns:
        df[column_name] = df[column_name].fillna(df[column_name].mean())

In [4]:
df = pd.concat(total_df_list,axis=0)

In [5]:
import pandas as pd
import numpy as np
import statsmodels.api as sma

In [6]:
feature_list = list(df.columns)
feature_list.remove('model')


In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
model = LogisticRegression()
model.fit(df[feature_list],df['model'])
model.predict(df[feature_list])

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2,
       0, 0, 0, 2, 0, 2, 2, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 3, 0, 1, 0,
       0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 3, 0, 0, 0, 0, 0, 3, 0,
       1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 2, 2, 2,
       0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 2, 0, 3, 0, 0, 3, 0, 0, 0, 1, 2, 3, 2, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 2, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 3, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,

In [9]:
from sklearn.metrics import accuracy_score
accuracy_score(model.predict(df[feature_list]),df['model'])

0.69901547116737

In [10]:
from sklearn.cluster import KMeans

In [11]:
model = KMeans(4)

In [12]:
model.fit(df[feature_list])

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=4, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [13]:
model.predict(df[feature_list])

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1,
       1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 3, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 3, 0, 0, 1, 1, 1, 1, 1, 3, 1, 1, 1, 3, 1,

In [14]:
df.corr()['model'].to_csv('corr_cluster.csv')

In [15]:
from sklearn import preprocessing

In [16]:
X_scaled = preprocessing.scale(df[feature_list])

In [17]:
X_scaled

array([[ 8.16499040e-01,  2.31722223e-02,  1.06474814e+00, ...,
        -2.13645793e-03,  1.45730051e-01,  1.34976100e-02],
       [-2.16356518e-01, -1.05420483e+00, -3.25453670e-01, ...,
        -3.42109195e-02, -4.62274251e-01, -4.83771976e-01],
       [ 3.34639449e-01, -3.61576247e-01,  5.35412783e-01, ...,
        -1.95750001e-02, -1.58272100e-01, -2.39055065e-01],
       ...,
       [ 1.52781874e-03, -5.40122312e-01,  4.68443573e-03, ...,
         2.46441605e-02, -2.08939125e-01, -2.39255982e-01],
       [ 4.80297886e-04, -2.09466387e-01, -5.52140392e-02, ...,
         1.18766563e-02, -2.34272637e-01, -2.91092569e-01],
       [-6.45840066e-01, -1.07698064e+00, -9.16080493e-01, ...,
        -2.29148909e-01, -2.59606150e-01, -2.96115494e-01]])

In [18]:
new_df = pd.DataFrame(X_scaled)

In [19]:
new_df.columns = df.columns[:-1]

In [20]:
new_df.corr()

总资产利润率(%)  主营业务利润率(%)  总资产净利润率(%)  成本费用利润率(%)  营业利润率(%)  \
总资产利润率(%)           1.000000    0.261576    0.962065    0.879225  0.803369   
主营业务利润率(%)          0.261576    1.000000    0.345491    0.110781  0.305231   
总资产净利润率(%)          0.962065    0.345491    1.000000    0.733494  0.722351   
成本费用利润率(%)          0.879225    0.110781    0.733494    1.000000  0.813962   
营业利润率(%)            0.803369    0.305231    0.722351    0.813962  1.000000   
...                      ...         ...         ...         ...       ...   
经营现金净流量对销售收入比率(%)   0.089188    0.201281    0.136722    0.017736  0.390489   
资产的经营现金流量回报率(%)     0.247721    0.220949    0.336413    0.065319  0.162543   
经营现金净流量与净利润的比率(%)   0.037484    0.013900    0.042976    0.008730  0.017691   
经营现金净流量对负债比率(%)     0.231999    0.299516    0.310829    0.085732  0.132625   
现金流量比率(%)           0.219173    0.297532    0.293330    0.092629  0.132548   

                   主营业务成本率(%)  销售净利率(%)  净资产收益率(%)  股本报酬率(%)  净资产报酬率(%)  ...  \
总资产利润率(%)           -0.252368  0.861689   0.408530  0.541299   0.036396  ...   
主营业务利润率(%)          -0.996521  0.101738   0.313985  0.214906   0.022951  ...   
总资产净利润率(%)          -0.334950  0.708427   0.541651  0.611535   0.051898  ...   
成本费用利润率(%)          -0.106628  0.983167   0.120399  0.373152   0.007964  ...   
营业利润率(%)            -0.260334  0.874960   0.239498  0.353775   0.003862  ...   
...                       ...       ...        ...       ...        ...  ...   
经营现金净流量对销售收入比率(%)   -0.161633  0.082162   0.172695  0.087184  -0.004384  ...   
资产的经营现金流量回报率(%)     -0.214174  0.052557   0.329926  0.292352   0.006681  ...   
经营现金净流量与净利润的比率(%)   -0.014144  0.007400   0.257019  0.040012   0.682289  ...   
经营现金净流量对负债比率(%)     -0.298943  0.051784   0.233743  0.176628   0.015774  ...   
现金流量比率(%)           -0.298056  0.051344   0.225272  0.164810   0.016680  ...   

                   总资产周转率(次)  存货周转天数(天)  总资产周转天数(天)  流动资产周转率(次)  流动资产周转天数(天)  \
总资产利润率(%)           0.195267  -0.135153   -0.456952    0.100545    -0.547769   
主营业务利润率(%)         -0.162879   0.219462   -0.166562   -0.178090    -0.010423   
总资产净利润率(%)          0.248913  -0.119983   -0.442646    0.111248    -0.491748   
成本费用利润率(%)          0.037892  -0.124672   -0.394515    0.035814    -0.559768   
营业利润率(%)            0.090131  -0.106787   -0.680859    0.079951    -0.642580   
...                      ...        ...         ...         ...          ...   
经营现金净流量对销售收入比率(%)   0.046343  -0.071208   -0.568270    0.077820    -0.413166   
资产的经营现金流量回报率(%)     0.145617  -0.102392   -0.200302    0.191955    -0.191810   
经营现金净流量与净利润的比率(%)   0.001473   0.002447   -0.005015    0.021955    -0.014523   
经营现金净流量对负债比率(%)     0.010039  -0.027320   -0.113997   -0.026165    -0.072713   
现金流量比率(%)          -0.024952  -0.029957   -0.084250   -0.009389    -0.066736   

                   经营现金净流量对销售收入比率(%)  资产的经营现金流量回报率(%)  经营现金净流量与净利润的比率(%)  \
总资产利润率(%)                   0.089188         0.247721           0.037484   
主营业务利润率(%)                  0.201281         0.220949           0.013900   
总资产净利润率(%)                  0.136722         0.336413           0.042976   
成本费用利润率(%)                  0.017736         0.065319           0.008730   
营业利润率(%)                    0.390489         0.162543           0.017691   
...                              ...              ...                ...   
经营现金净流量对销售收入比率(%)           1.000000         0.407258           0.043080   
资产的经营现金流量回报率(%)             0.407258         1.000000           0.126229   
经营现金净流量与净利润的比率(%)           0.043080         0.126229           1.000000   
经营现金净流量对负债比率(%)             0.262802         0.664118           0.048052   
现金流量比率(%)                   0.287936         0.685714           0.055965   

                   经营现金净流量对负债比率(%)  现金流量比率(%)  
总资产利润率(%)                 0.231999   0.219173  
主营业务利润率(%)                0.299516   0.297532  
总资产净利润率(%)                0.310829   0.293330  
成本费用利润率(%)                0.085732   0.092629  
营业利润率(%

In [21]:
eig_value, eig_vector = np.linalg.eig(new_df.corr())

In [22]:
df2 = pd.DataFrame(eig_value.cumsum()/sum(eig_value))

In [23]:
df2.index = new_df.columns

In [24]:
df2.to_csv('eig_value_cumsum.csv')

In [25]:
feature = new_df.columns[:44]

In [26]:
model = KMeans(4)

In [27]:
model.fit(new_df[feature])

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=4, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [28]:
model.predict(new_df[feature])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [29]:
model = KMeans(4)
model.fit(new_df[feature])
model.predict(new_df[feature])

array([2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 3, 2, 1, 1, 1,
       1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 2, 1, 3, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1,
       2, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1,
       1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1,
       0, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 0, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [30]:
feature

Index(['总资产利润率(%)', '主营业务利润率(%)', '总资产净利润率(%)', '成本费用利润率(%)', '营业利润率(%)',
       '主营业务成本率(%)', '销售净利率(%)', '净资产收益率(%)', '股本报酬率(%)', '净资产报酬率(%)',
       '资产报酬率(%)', '销售毛利率(%)', '三项费用比重(%)', '非主营比重(%)', '主营利润比重(%)', '流动比率(%)',
       '速动比率(%)', '现金比率(%)', '利息支付倍数(%)', '资产负债率(%)', '长期债务与营运资金比率(%)',
       '股东权益比率(%)', '长期负债比率(%)', '股东权益与固定资产比率(%)', '负债与所有者权益比率(%)',
       '长期资产与长期资金比率(%)', '资本化比率(%)', '固定资产净值率(%)', '资本固定化比率(%)', '产权比率(%)',
       '清算价值比率(%)', '固定资产比重(%)', '主营业务收入增长率(%)', '净利润增长率(%)', '净资产增长率(%)',
       '总资产增长率(%)', '基本每股收益(元)', '每股净资产(元)', '每股经营活动产生的现金流量净额(元)',
       '主营业务收入(万元)', '主营业务利润(万元)', '营业利润(万元)', '投资收益(万元)', '营业外收支净额(万元)'],
      dtype='object')

In [31]:
from sklearn.metrics import jaccard_score,davies_bouldin_score

In [32]:
jaccard_score(model.predict(new_df[feature]),df['model'],average='macro')

0.17093457441807364

In [33]:
davies_bouldin_score(new_df[feature],
                     model.predict(new_df[feature]))

1.6562160258094396

In [34]:
from sklearn.cluster import AgglomerativeClustering
ac=AgglomerativeClustering(n_clusters=4)

In [35]:
predict = ac.fit_predict(new_df[feature])

In [36]:
jaccard_score(predict,df['model'],average='macro')

0.09312717791872446

In [37]:
davies_bouldin_score(new_df[feature],
                     predict)

0.5587845713132813

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
train_x, test_x, train_y, test_y = train_test_split(df[feature_list],df['model'])

In [40]:
from sklearn import discriminant_analysis
lda=discriminant_analysis.LinearDiscriminantAnalysis()
lda.fit(train_x,train_y)
print('Coefficients:%s, intercept %s'%(lda.coef_,lda.intercept_))#输出权重向量和b
print('Score: %.2f' % lda.score(test_x, test_y))#测试集
print('Score: %.2f' % lda.score(train_x, train_y))#训练集

Coefficients:[[-2.18540172e-02  6.38947460e-02 -3.08448976e-01  9.89043524e-03
  -5.77687540e-02  8.03370446e-02  1.39921550e-02 -2.38195469e-01
  -1.07932384e-02  3.99735777e-03  3.14745641e-01  9.44089661e-03
  -6.40190386e-02  1.34960059e-03 -1.39696067e-05 -2.66656158e-02
   8.11803829e-02 -2.18635396e-05 -6.65988415e-06  5.03388363e-03
   6.22527208e-03 -5.02958638e-03 -2.19364830e-02  6.10199576e-05
   3.12237837e-03 -7.24767992e-03 -3.03179702e-03  2.27457418e-02
  -1.53025875e-03 -4.43858858e-03 -1.39030210e-03 -2.12409169e-02
   6.99500463e-04  2.09622903e-04 -1.75808777e-04  1.64797457e-03
   1.22842226e+00 -9.44735998e-03 -6.39401726e-02  1.41316759e-07
   8.49802072e-07 -2.01688389e-06  7.24525205e-07 -5.54619631e-05
  -5.58398064e-06  1.04592087e-05 -1.43461588e-06  1.36272023e-06
   7.63892272e-07  7.51295683e-07 -3.01416952e-07 -7.70613498e-07
   2.28438263e-07 -1.09917507e-06  2.84437513e-01 -1.99519822e-02
   2.16376498e-03 -9.12246212e-05  2.46346175e-02 -4.24743885e-

In [41]:
test_y

7      3
166    2
6      1
92     1
62     1
      ..
30     2
16     2
6      0
34     1
134    2
Name: model, Length: 178, dtype: int64

In [42]:
train_x, test_x, train_y, test_y = train_test_split(df[feature],df['model'])
lda=discriminant_analysis.LinearDiscriminantAnalysis()
lda.fit(train_x,train_y)
print('Coefficients:%s, intercept %s'%(lda.coef_,lda.intercept_))#输出权重向量和b
print('Score: %.2f' % lda.score(test_x, test_y))#测试集
print('Score: %.2f' % lda.score(train_x, train_y))#训练集

Coefficients:[[-4.44056820e-01  2.83446907e-01  8.69119936e-02  1.02278071e-02
  -2.98601376e-02  3.10479532e-01  1.02209684e-02 -3.13472133e-02
  -1.23355529e-02 -5.00747088e-03  3.94249444e-01  1.72067134e-03
  -1.62352102e-02  4.24051842e-04 -2.29887926e-05 -5.75103153e-02
   1.24813562e-01 -6.18903026e-04 -9.61556137e-06  2.16746214e-03
   4.67274103e-03 -2.19701093e-03 -2.76123134e-03  1.52073075e-04
   4.08696032e-03 -1.29085189e-03 -3.91349792e-03  1.99919313e-02
  -1.01125784e-02  4.74830841e-04 -9.46240698e-04 -1.43189740e-02
  -1.24865146e-03  1.82117309e-04 -1.43671335e-03  3.05901191e-03
   1.47845009e+00 -6.74854646e-03 -2.44248752e-02 -5.43606630e-08
   6.30565179e-07 -1.19902864e-06  8.57303610e-07 -2.11560144e-05]
 [-1.30908001e-01 -3.34848576e-01 -9.07493684e-02  4.68526112e-02
   1.82353074e-01 -2.17270453e-01 -1.32613612e-01  3.40606433e-02
  -1.26804076e-03 -1.68882005e-02  5.61884493e-02 -1.29970960e-02
   4.89221187e-02 -4.30490820e-04 -2.99865964e-05 -1.12549415e

In [43]:
from sklearn.metrics import precision_score, recall_score, f1_score
def show_reason(predict,label):
    for i in range(np.unique(label).shape[0]):
        tp = ((predict == i) & (test_y == i)).sum()
        tn = ((predict != i) & (test_y != i)).sum()
        fn = ((predict != i) & (test_y == i)).sum()
        fp = ((predict == i) & (test_y != i)).sum()
        print('{}tp:{} tn:{},fn:{},fp:{}'.format(i,tp,tn,fn,fp))
    print(precision_score(predict,label,average='macro'))
    print(recall_score(predict,label,average='macro'))
    print(f1_score(predict,label,average='macro'))

In [44]:
from sklearn.svm import SVC

In [45]:
svm_model = SVC()
svm_model.fit(train_x,train_y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [46]:
svm_model.score(test_x,test_y)
show_reason(svm_model.predict(test_x), test_y)

0tp:59 tn:4,fn:0,fp:115
1tp:1 tn:148,fn:29,fp:0
2tp:1 tn:127,fn:50,fp:0
3tp:2 tn:140,fn:36,fp:0
0.27639318885448916
0.8347701149425287
0.17735385893353495


In [47]:
from sklearn.ensemble import RandomForestClassifier

In [48]:
model = RandomForestClassifier(n_estimators=200,min_samples_split=5,random_state=11)
model.fit(train_x,train_y)
model.score(test_x,test_y)
show_reason(model.predict(test_x), test_y)

0tp:45 tn:87,fn:14,fp:32
1tp:19 tn:144,fn:11,fp:4
2tp:43 tn:117,fn:8,fp:10
3tp:14 tn:129,fn:24,fp:11
0.6519008763184131
0.6954558239135762
0.6625283398313364


In [49]:
from sklearn.tree import DecisionTreeClassifier

In [50]:
model = DecisionTreeClassifier()

In [51]:
model.fit(train_x,train_y)
show_reason(model.predict(test_x), test_y)

0tp:34 tn:86,fn:25,fp:33
1tp:14 tn:140,fn:16,fp:8
2tp:39 tn:115,fn:12,fp:12
3tp:14 tn:116,fn:24,fp:24
0.5440161970229661
0.5692383144788301
0.5528177532821495


In [52]:
from sklearn.neural_network import MLPClassifier

In [53]:
model = MLPClassifier(hidden_layer_sizes=(200,))

In [54]:
model.fit(train_x,train_y)
model.score(test_x,test_y)

0.5449438202247191

In [55]:
predict = model.predict(test_x)

In [56]:
show_reason(predict, test_y)

0tp:44 tn:65,fn:15,fp:54
1tp:10 tn:141,fn:20,fp:7
2tp:36 tn:115,fn:15,fp:12
3tp:7 tn:132,fn:31,fp:8
0.4922972311136765
0.5634703881552621
0.49436628492567447
